# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc00e36ebf1ca017d545ca96e65eedfad2b5afa63eb890b2534b0224d853bbf696a3e8c4fbba5f064d582fb28902674ee7a04bdc366551aea8e32e0c0538bd14

test:
  secret_key_base: 53eb93b2459ec2fb11b0d7020e7e5826415fab98692d1d6f0382a292b1e9725eaeb3e09b6ae24090f13e538d053a66a3f07afa2b29b110b379fe7c8801aff1c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
